#include "BlockDefinitionMacros.h"

#define DEFAULT_BLOCK_MARKER_SIZE 23.f



// Cozmo Active Block #1
START_BLOCK_DEFINITION(LIGHTCUBE1, (44.f,44.f,44.f), ORANGE)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_FRONT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_BACK,PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_LEFT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_RIGHT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_TOP, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEI_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Cozmo Active Block #2
START_BLOCK_DEFINITION(LIGHTCUBE2, (44.f,44.f,44.f), YELLOW)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_FRONT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_BACK,PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_LEFT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_RIGHT, PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_TOP, PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEJ_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Cozmo Active Block #3
START_BLOCK_DEFINITION(LIGHTCUBE3, (44.f,44.f,44.f), RED)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBEK_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// Vector Active Block #1
START_BLOCK_DEFINITION(LIGHTCUBE4, (44.f,44.f,44.f), GREEN)
ADD_FACE_CODE(FRONT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_FRONT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(BACK_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_BACK,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(LEFT_FACE,   DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_LEFT,   PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(RIGHT_FACE,  DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_RIGHT,  PreActionOrientation::UP | PreActionOrientation::DOWN)
ADD_FACE_CODE(TOP_FACE,    DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_TOP,    PreActionOrientation::NONE)
ADD_FACE_CODE(BOTTOM_FACE, DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_LIGHTCUBE_CIRCLE_BOTTOM, PreActionOrientation::ALL)
END_BLOCK_DEFINITION

// "Ghost" Active Block - NOT FOR USE IN BLOCKWORLD
START_BLOCK_DEFINITION(LIGHTCUBE_GHOST, (44.f,44.f,44.f), WHITE)
ADD_ALL_FACES(DEFAULT_BLOCK_MARKER_SIZE, Vision::MARKER_UNKNOWN)
END_BLOCK_DEFINITION

#undef DEFAULT_BLOCK_MARKER_SIZE
